In [6]:
import pandas as pd
import numpy as np
from pathlib import Path

In [7]:
DATA_DIR = Path.cwd().parent / "estimates"


def load_result(model: str, method: str) -> np.ndarray:
    arr = np.load(DATA_DIR / f"{model}_{method}.npy", allow_pickle=True)
    print(arr.shape)
    return arr

In [8]:
for name in ["times_exact.npy", "times_kernel.npy", "times_uks.npy"]:
    print(np.load(Path.cwd().parent / name, allow_pickle=True))

[48.26709557 74.68177319  2.55753422]
[315.73649549 541.628793    99.40922451]
[[ 68.36794996  70.16046238  71.32849288  71.06542039 129.23967791]
 [ 82.03080273  81.57967925  79.76588106  80.50075841 161.99366498]
 [  9.83904243   9.76248479   9.4830935    9.70629406  14.85238791]]


In [9]:
MODELS = ["random_forest", "support_vector_machine", "logistic_regression"]
METHODS = ["10", "50", "100", "500", "1000", "kernel", "exact"]

In [10]:
for model in MODELS:
    for method in METHODS:
        load_result(model, method)

(331,)
(331,)
(331,)
(331,)
(331,)
(331, 8)
(331, 8)
(331,)
(331,)
(331,)
(331,)
(331,)
(331, 8)
(331, 8)
(331,)
(331,)
(331,)
(331,)
(331,)
(331, 8)
(331, 8)
